name: Class Diagram

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  diagram:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: sudo apt-get update
      - run: sudo apt-get install -y graphviz

      - run: pip install pylint

      - run: |
          pyreverse models \
            -o png \
            -p Modelos

      - uses: actions/upload-artifact@v4
        with:
          name: diagrama-clases
          path: classes_Modelos.png