name: Class Diagram

on:
  push:
  workflow_dispatch:

jobs:
  diagram:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Instalar dependencias
        run: |
          pip install pylint

      - name: Generar DOT con pyreverse
        run: |
          mkdir -p build

          pyreverse models \
            -ASmy \
            -o dot \
            -p Modelos \
            -d build

      - name: Modificar el DOT
        run: |
          python scripts/modificar_dot.py

      - name: Generar PNG
        run: |
          dot \
            -Tpng \
            classes_Modelos.dot \
            -o docs/class_diagram.png

      - name: Commit del nuevo diagrama
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/class_diagram.png

          if git diff --cached --quiet; then
            echo "No hubo cambios en el diagrama."
          else
            git commit -m "Actualizar diagrama de clases"
            git push
          fi